"""Redis-backed session service.

Session lifecycle
-----------------
Sessions are stored in Redis as JSON hashes under the key
``session:{session_id}``.  The session ID is a 32-byte cryptographically
random hex string (64 hex chars), generated by :func:`secrets.token_hex`.

On every authenticated request :meth:`SessionService.get` is called.  If the
session exists its TTL is renewed (sliding window).  If it does not exist
(expired or revoked) ``None`` is returned and the caller raises HTTP 401.

Revocation is immediate: :meth:`SessionService.delete` removes the key from
Redis so the session is invalid on the next request.

Key schema
----------
    session:{session_id}  →  JSON {"user_id", "username", "display_name",
                                    "email", "is_admin"}
    TTL: STRATA_SESSION_TTL_SECONDS (reset on every get)
"""

import json
import logging
import secrets

from redis.asyncio import Redis

from strata.sessions.schemas import SessionData

L = logging.getLogger(__name__)

_KEY_PREFIX = "session:"


def _key(session_id: str) -> str:
    return f"{_KEY_PREFIX}{session_id}"


class SessionService:
    """Manage authenticated sessions in Redis.

    Instantiated once at application startup and stored on ``app.state``.
    Injected into request handlers via :mod:`strata.sessions.deps`.

    Args:
        redis: An open async Redis client.
        ttl_seconds: Session time-to-live in seconds.  The TTL is reset on
            every successful :meth:`get` call (sliding window).
    """

    def __init__(self, redis: Redis, ttl_seconds: int) -> None:  # type: ignore[type-arg]
        self._redis = redis
        self._ttl = ttl_seconds

    # ── Public API ─────────────────────────────────────────────────────────────

    async def create(self, data: SessionData) -> str:
        """Persist a new session and return the opaque session ID.

        The caller is responsible for setting the session cookie on the
        HTTP response using
        :func:`~strata.dependencies.auth.session_cookie_helper`.

        Args:
            data: Session payload to store.

        Returns:
            A 64-character hex session ID suitable for use as a cookie value.
        """
        session_id = secrets.token_hex(32)
        payload = json.dumps(
            {
                "user_id": data.user_id,
                "username": data.username,
                "display_name": data.display_name,
                "email": data.email,
                "is_admin": data.is_admin,
            }
        )
        await self._redis.set(_key(session_id), payload, ex=self._ttl)
        L.debug("Created session for user %r", data.user_id)
        return session_id

    async def get(self, session_id: str) -> SessionData | None:
        """Look up a session, renew its TTL, and return the session data.

        Returns ``None`` if the session does not exist or has expired.

        Args:
            session_id: The opaque session ID from the cookie.

        Returns:
            :class:`SessionData` if the session is valid, ``None`` otherwise.
        """
        raw = await self._redis.getex(_key(session_id), ex=self._ttl)
        if raw is None:
            return None
        try:
            payload = json.loads(raw)
            return SessionData(
                user_id=payload["user_id"],
                username=payload["username"],
                display_name=payload["display_name"],
                email=payload.get("email"),
                is_admin=payload.get("is_admin", False),
            )
        except json.JSONDecodeError, KeyError:
            L.warning("Malformed session payload for id %r — discarding", session_id)
            await self._redis.delete(_key(session_id))
            return None

    async def delete(self, session_id: str) -> None:
        """Revoke a session immediately.

        Safe to call with an already-expired or non-existent session ID.

        Args:
            session_id: The opaque session ID to revoke.
        """
        await self._redis.delete(_key(session_id))
        L.debug("Deleted session %r", session_id)

    async def ping(self) -> bool:
        """Return True if the Redis connection is healthy."""
        try:
            return bool(await self._redis.ping())  # type: ignore
        except Exception:
            return False
