"""Image preview plugin for Strata.

A hybrid plugin that:

- **Backend**: exposes a ``/thumbnail`` endpoint (currently a passthrough;
  a real implementation would resize via Pillow).
- **Frontend**: registers a previewer for common raster and vector image
  formats.

Handled extensions:
    ``.png``, ``.jpg``, ``.jpeg``, ``.gif``, ``.webp``, ``.svg``, ``.bmp``
"""

import os
from pathlib import Path
from typing import Annotated

from fastapi import APIRouter, HTTPException, Query
from fastapi.responses import FileResponse

from strata.plugins.base import BackendPlugin

router = APIRouter(prefix="/api/plugins/image_preview", tags=["image_preview"])

_IMAGE_EXTS: frozenset[str] = frozenset({".png", ".jpg", ".jpeg", ".gif", ".webp", ".svg", ".bmp"})
_ROOT: Path = Path(os.environ.get("STRATA_LOCAL_ROOT", Path.home())).resolve()


@router.get("/thumbnail")
def get_thumbnail(
    path: Annotated[str, Query(description="Backend-relative image path")],
) -> FileResponse:
    """Serve an image file for preview.

    In a production implementation this endpoint would accept a ``size``
    parameter and return a resized thumbnail generated by Pillow.  For
    now it serves the original file directly.

    Args:
        path: Backend-relative path to the image.

    Returns:
        A ``FileResponse`` streaming the image bytes.

    Raises:
        HTTPException: 403 if the path escapes the root; 404 if the
            file does not exist or is not a recognised image type.

    """
    target = (_ROOT / path.lstrip("/")).resolve()
    if not target.is_relative_to(_ROOT):
        raise HTTPException(status_code=403, detail="Access denied")
    if not target.exists() or target.suffix.lower() not in _IMAGE_EXTS:
        raise HTTPException(status_code=404, detail="Not an image")
    return FileResponse(target)


class ImagePreviewPlugin(BackendPlugin):
    """Hybrid plugin that adds server-side thumbnails and a frontend image previewer.

    Capabilities:
        preview: Registers a frontend previewer component for image files.
    """

    id: str = "image_preview"
    name: str = "Image Preview"
    version: str = "0.1.0"
    description: str = "In-browser preview for common image formats."
    handles: list[str] = [".png", ".jpg", ".jpeg", ".gif", ".webp", ".svg", ".bmp"]  # noqa: RUF012

    def get_router(self) -> APIRouter:
        """Return the router exposing the ``/thumbnail`` endpoint."""
        return router

    def get_capabilities(self) -> list[str]:
        """Return ``["preview"]``."""
        return ["preview"]


plugin = ImagePreviewPlugin()
